language: node_js

node_js:
  - stable

install:
  - yarn

script:
  - yarn test:unit -- --coverage && yarn test:snapshot -- --coverage && yarn test:cypress

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls